### ISSUE TITLE
Referenced Version of ces-qt-browser not available

### ISSUE THREAD

**Issue by ursfassler** [software-celo/meta-ces#1]
In the recipe `ces-qt-browser_2.0.bb` of the branch `warrior` the hash `6a6ad26f030ddbfb2494f394236c5dae787494a6` is referenced but not found in the corresponding repository. Therefore, the browser and image `ces-qt-demoimage` can not be built.

**Comment by pfink-christ** [comment]
Hi Urs,
the `warrior` branch is not totally ready yet, sorry.
Until it is not referenced in software-celo/ces-bsp-platform it might be subject to further changes or may not build entirely. There are still some commits queued for release on github.
I hope we will be able to push them all out until the end of the week.
Thanks for your patience! =)
Peter

**Comment by ursfassler** [comment]
No problem, I am primarily interested in the boot-loader and kernel.
